### ISSUE TITLE
Transaction is not being forwarded to all the peers after (what we think a reorganization).

### ISSUE THREAD

**Issue by ignaciopulicedonatto** [rsksmart/rskj#1127] opened 2019-12-19 17:21 UTC
**Overview**: 
We have a script that sends a transaction every certain time (time doesn’t matter except you can reproduce it quicker if time is short between requests).

**Debugging steps**: 
1) Transaction is send to node
2) Transaction is accepted, everything looks good with the transaction
3) Transaction is send to the peers 
4) Transaction comes in one block mined.
5) There are several reorganization in the network that affect the mined block.
transaction should be added again into txpool.
6) From here this transaction is never mined again.
7) We send a new transaction with the same hash (same nonce, same price, same everything) so hash is the same as the previous one.
8) Up to here nothing happens and the new transaction will never get mined.

**Things we believe is happening**:
1) Transaction with the same hash was previously sent and our node doesn't resend it because it has been sent to all the peers. 
(TransactionNodeInFormation.java method addTransactionNode saves a map key-pair for every transaction it has, a set of node friends, this starts to clean after reaching 1000 transactions).
Peers friends may have the same problem when they receive transactions with the same hash, they discard it because they already received it.
2) Reorganization is discarding/losing original transaction. For some reason, that we don’t know, this transaction is never added in one block to mine after reorganizations. This reorganization at certain heights happens 3 times as we could see ( IMPORTED_BEST blocks). And then it never gets mined again.

**Up to here, we think there is more than one bug**. 
1) The transaction with the same hash should be able to resend it to the network after a period of time.
2) In reorganizations, transactions are being discarded or lost.

**Things we had tried to workaround the bug**:
Workaround 1. We tried to restart the node, nothing happened almost every time. 
Workaround 2. Every time we build the transaction we change the price a little bit (adding a random value) to change the value of the hash, and that works.

I uploaded all the logs (script.log,  rsk.log) in a [drive](https://drive.google.com/open?id=1mm5ma2x6D0nsgAVkr79vXux-e0pkACpz). With this you can see that the first time we get an ERROR in ourscript.log there is a reorganization at that time. When a reorganization happens for block X you will see in rsk.log that there are 3 IMPORTED_BEST  for that block.
The raw transaction is printed in script.log, so you can start from that point.

**Comment by ajlopez** [comment] 2020-04-30 16:29
The transaction is forwarded to all the peers of the node, when it is received and validated. There is no need to forward the transaction again.

Another cause for not having the transaction mined again, could the obsolescence transaction time. If the transaction becomes obsolete (being too old), then it will not be processed again. Maybe, "many reorganizations" allows the expiration of the transaction BEFORE being mined again. But then, the reorganizations are not the root cause: the root cause is the low obsolescence time. In geth, the lifetime is 3 hours. See https://ethereum.stackexchange.com/questions/39510/why-would-a-transaction-be-dropped-from-transaction-pool

**Comment by ajlopez** [comment] 2020-04-30 16:33
Currently, the forwarding logic complicates the process of obsolescence transactions. Even when `TransactionPoolImpl` accepts transactions that replaces the obsolete ones, `TransactionGateway` don't allow the forwarding: this class has no notion of obsolete transaction.

Recommendation: remove this gateway class. There is no need to keep a registry of nodes that already received this transaction.

**Comment by AlanVerbner** [comment] 2020-05-12 08:15
hi! I think we might been struggling with this issue as well or at lease something similar as our transaction never gets mined. The workaround 2 seems to be working so far although some re-sends took 25 to 40 blocks to get mined.

- We are connecting to testnet using this rskj version https://github.com/rsksmart/artifacts/commit/92c29747b78656ebf2d383788e7a6079c87dcdc0
-  We are setting at least `0.063 gwei` so we think it's not related to gas price

Do you have any hint so we can take a look at our node logs to check if this is the case?

**Comment by fedejinich** [comment] 2020-07-17 15:59
shall we close this issue?

**Closed** 2021-11-02 20:03 UTC
Labels: bug, core :atom_symbol:
