### ISSUE TITLE
Inheritance/Function Modifiers seems not working properly

### ISSUE THREAD

**Issue by y0ke** [rsksmart/rskj#75] opened 2017-05-30 09:18 UTC
My contract uses Inheritance and Function Modifiers. Which is something like below

```
contract Bar is Foo {
  ....
  function setFooAddress(address _fooAddress) onlyWorking {
    ....
  }
}
```

`onlyWorking` comes from 

```
contract Foo {
    function ownerValidate(address addr) constant returns (bool);
    bool public isWorking;

    function Owned() {
        isWorking = true;
    
    modifier onlyWorking {
        if (!isWorking) throw;
        //_;
        _
    }

    function setWorking(bool _isWorking) onlyOwner {
        isWorking = _isWorking;
    }
}
```

It seems works properly until once `isWorking` is changed, contract Bar's almost all functions returns wrong value after `isWorking` is changed.
the contract works great in Ethereum.

I'm wondering `setWorking` changes wrong position of the storage data though I'm not sure.

**Comment by ajlopez** [comment] 2017-06-07 15:39
Thanks for your reporting!

We reproduced the issue, with and without using modifier. Can you check the value of isWorking, AFTER CHANGING it?

In our issue reproduction, after the change of isWorking variable,  we get the value and it was not changed. Is it your case?

**Comment by y0ke** [comment] 2017-06-08 05:12
A state remains the same after calling `setWorking`.
I haven't checked the corresponding data position in its storage.So I'm not sure whether it updates proper position of storage or not. But one thing for sure is that I can't get any other variable's value after changing it. as far as I know, other variables starts returning null after calling `setWorking`. of course they have non-null value originally.

**Comment by ajlopez** [comment] 2017-06-16 19:21
We are working on the issue. We found one root cause. The solution will be included in an upcoming release (I'm not sure about the release date, yet), But it is related to our storage algorithms,

Your report helped us a lot, thanks!

**Closed** 2018-06-11 19:33 UTC
Labels: core
