### ISSUE TITLE
Can't get node's public IP address from checkip.amazonaws.com

### ISSUE THREAD

**Issue by varshard** [rsksmart/rskj#633] opened 2018-08-20 15:57 UTC
I followed instructions on https://github.com/rsksmart/rskj/wiki/install-rskj-using-fat-jar.

When I execute
`java -cp rskj-core-0.4.4-BAMBOO-all.jar co.rsk.Start`

I got following errors
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/Users/bhoomtawathplinsut/jars/rskj-core-0.4.4-BAMBOO-all.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/Users/bhoomtawathplinsut/jars/rskj-core-0.4.4-BAMBOO-all.jar!/org/ethereum/net/NodeManager.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [co.rsk.net.discovery.PeerExplorer]: Error creating bean with name 'peerExplorer' defined in org.ethereum.config.DefaultConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [co.rsk.net.discovery.PeerExplorer]: Factory method 'peerExplorer' threw exception; nested exception is java.lang.RuntimeException: Wildcard on bind address it's not allowed as fallback for public IP /0.0.0.0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'peerExplorer' defined in org.ethereum.config.DefaultConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [co.rsk.net.discovery.PeerExplorer]: Factory method 'peerExplorer' threw exception; nested exception is java.lang.RuntimeException: Wildcard on bind address it's not allowed as fallback for public IP /0.0.0.0
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1148)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:778)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:843)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at co.rsk.SpringNodeBootstrapper.<init>(SpringNodeBootstrapper.java:43)
	at co.rsk.Start.main(Start.java:31)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'peerExplorer' defined in org.ethereum.config.DefaultConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [co.rsk.net.discovery.PeerExplorer]: Factory method 'peerExplorer' threw exception; nested exception is java.lang.RuntimeException: Wildcard on bind address it's not allowed as fallback for public IP /0.0.0.0
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1021)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:814)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 14 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [co.rsk.net.discovery.PeerExplorer]: Factory method 'peerExplorer' threw exception; nested exception is java.lang.RuntimeException: Wildcard on bind address it's not allowed as fallback for public IP /0.0.0.0
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 27 more
Caused by: java.lang.RuntimeException: Wildcard on bind address it's not allowed as fallback for public IP /0.0.0.0
	at org.ethereum.config.SystemProperties.getMyPublicIpFromRemoteService(SystemProperties.java:568)
	at org.ethereum.config.SystemProperties.getPublicIp(SystemProperties.java:540)
	at org.ethereum.config.DefaultConfig.peerExplorer(DefaultConfig.java:210)
	at org.ethereum.config.DefaultConfig$$EnhancerBySpringCGLIB$$befa31d5.CGLIB$peerExplorer$9(<generated>)
	at org.ethereum.config.DefaultConfig$$EnhancerBySpringCGLIB$$befa31d5$$FastClassBySpringCGLIB$$631f1e02.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at org.ethereum.config.DefaultConfig$$EnhancerBySpringCGLIB$$befa31d5.peerExplorer(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 28 more
```

**Comment by varshard** [comment] 2018-08-21 14:55
@tinchou Thanks. This just work.
Should the line be added to the wiki?

**Comment by juli** [comment] 2018-08-22 17:37
From your Gitter message looks like you are behind a transparent proxy that is adding a `X-Forwarded-For` header and Amazon's `checkip.amazonaws.com` service returns two IP addresses separated by `,` instead of a single address. The rskj code to obtain the node's public IP does not understand the answer and fails.

```2018-08-20-15:16:26.136 INFO [config]  Config ( yes ): user properties from -Drsk.conf.file file '/etc/rsk/node.conf'
2018-08-20-15:16:26.180 INFO [config]  Config ( yes ): default properties from installer '/etc/rsk/node.conf'
2018-08-20-15:16:27.155 INFO [general]  Public IP wasn't set or resolved, using checkip.amazonaws.com to identify it...
2018-08-20-15:16:27.779 ERROR [general]  Can't get public IP
java.lang.IllegalArgumentException: Invalid address: '171.99.160.48, 171.99.160.48'
    at org.ethereum.config.SystemProperties.tryParseIpOrThrow(SystemProperties.java:736)
    at org.ethereum.config.SystemProperties.getMyPublicIpFromRemoteService(SystemProperties.java:557)
    at org.ethereum.config.SystemProperties.getPublicIp(SystemProperties.java:540)
    at org.ethereum.config.DefaultConfig.peerExplorer(DefaultConfig.java:210)
...
```

Setting `bind_address = 127.0.0.1` does not solve the problem because you won't be able to receive incoming p2p connections from nodes. You can set the bind address to  `171.99.160.48` your public IP address or set your public IP manually: `public.ip = 171.99.160.48` and leave the default `bind_address = 0.0.0.0` value.

Try obtaining your IP from Amazon to reproduce the problem `curl checkip.amazonaws.com`

rskj code should be fixed to parse correctly `checkip.amazonaws.com` responses and also obtain the public IP address from the local network interfaces.

**Closed** 2019-07-24 19:11 UTC
Labels: core :atom_symbol:
